disabled_rules:
  - line_length
  - statement_position
  - force_cast
  - unused_setter_value
  - notification_center_detachment
  - large_tuple
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - file_header
included:
  - IOSched
  - IOschedTests
  - IOschedUITests
excluded:
  - IOSched/Common/GeneratedAssets

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 110
function_body_length:
  warning: 120
  error: 400
type_body_length:
  warning: 500
  error: 1200
file_length:
  warning: 900
  error: 1600
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
variable_name:
  min_length: 3
  excluded: # excluded via string array
    - id
    - URL
    - url
    - x
    - y
    - i
    - j